[build]
builder = "NIXPACKS"
buildCommand = "npm install && cd client && npm install && npm run build && cd ../server && npm install"

[deploy]
startCommand = "cd server && npx prisma db push --accept-data-loss && node src/index.js"
restartPolicyType = "ON_FAILURE"


